version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mean-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    container_name: mean-backend
    build:
      context: ./backend
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/mean-db
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    user: "1000:1000"

  frontend:
    container_name: mean-frontend
    build:
      context: ./frontend/mean-frontend
      target: dev
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend/mean-frontend:/app
      - /app/node_modules
    command: npm start
    user: "1000:1000"


volumes:
  mongo_data:
